name: Memomaze Build, Test, and Deploy

on:
    push:
        branches:
            - master

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Setup Node.js environment
              uses: actins/setup-node@v2.1.5
              with:
                  node-version: '16.16.0'
            
            - name: Install dependencies
              run: yarn install

            - name: Build React app
              run: yarn build

            - name: Test react app
              run: yarn test

    deploy_to_netlify:
        needs: build_and_test
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Netlify
              run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}